# Generated by Django 2.1.7 on 2023-09-08 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Expiry (YYYY-MM-DD)'),
        ),
    ]
